# NOTE: This code has been automatically generated by desilike.bindings.montepython.factory.MontePythonLikelihoodGenerator
from desilike.bindings.montepython.factory import MontePythonLikelihoodFactory

from desilike.bindings.base import load_from_file
DESICompressedBAOLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'DESICompressedBAOLikelihood')
desi_bao_bgs_z0 = MontePythonLikelihoodFactory(DESICompressedBAOLikelihood, 'desi_bao_bgs_z0', kw_like={'cosmo': 'external', 'tracers': ['bgs_z0'], 'version': 'v1.5'}, module=__name__)

