# NOTE: This code has been automatically generated by desilike.bindings.montepython.factory.MontePythonLikelihoodGenerator
from desilike.bindings.montepython.factory import MontePythonLikelihoodFactory

from desilike.bindings.base import load_from_file
DESIFSLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_fs_bao.py', 'DESIFSLikelihood')
desi_shapefit_joint_lrg_z2 = MontePythonLikelihoodFactory(DESIFSLikelihood, 'desi_shapefit_joint_lrg_z2', kw_like={'cosmo': 'external', 'data_name': '', 'observable_name': 'shapefit-joint', 'tracers': ['lrg_z2'], 'theory_name': 'reptvelocileptors'}, module=__name__)

