# NOTE: This code has been automatically generated by desilike.bindings.cobaya.factory.CobayaLikelihoodGenerator
from desilike.bindings.cobaya.factory import CobayaLikelihoodFactory

from desilike.bindings.base import load_from_file
DESICompressedBAOLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'DESICompressedBAOLikelihood')
desi_bao_all = CobayaLikelihoodFactory(DESICompressedBAOLikelihood, 'desi_bao_all', kw_like={'cosmo': 'external', 'tracers': None, 'version': 'v1.5'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
DESICompressedBAOLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'DESICompressedBAOLikelihood')
desi_bao_bgs_z0 = CobayaLikelihoodFactory(DESICompressedBAOLikelihood, 'desi_bao_bgs_z0', kw_like={'cosmo': 'external', 'tracers': ['bgs_z0'], 'version': 'v1.5'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
DESICompressedBAOLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'DESICompressedBAOLikelihood')
desi_bao_lrg_z0 = CobayaLikelihoodFactory(DESICompressedBAOLikelihood, 'desi_bao_lrg_z0', kw_like={'cosmo': 'external', 'tracers': ['lrg_z0'], 'version': 'v1.5'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
DESICompressedBAOLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'DESICompressedBAOLikelihood')
desi_bao_lrg_z1 = CobayaLikelihoodFactory(DESICompressedBAOLikelihood, 'desi_bao_lrg_z1', kw_like={'cosmo': 'external', 'tracers': ['lrg_z1'], 'version': 'v1.5'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
DESICompressedBAOLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'DESICompressedBAOLikelihood')
desi_bao_lrg_z2 = CobayaLikelihoodFactory(DESICompressedBAOLikelihood, 'desi_bao_lrg_z2', kw_like={'cosmo': 'external', 'tracers': ['lrg_z2'], 'version': 'v1.5'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
DESICompressedBAOLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'DESICompressedBAOLikelihood')
desi_bao_lrgpluselg_z0 = CobayaLikelihoodFactory(DESICompressedBAOLikelihood, 'desi_bao_lrgpluselg_z0', kw_like={'cosmo': 'external', 'tracers': ['lrgpluselg_z0'], 'version': 'v1.5'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
DESICompressedBAOLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'DESICompressedBAOLikelihood')
desi_bao_elg_z1 = CobayaLikelihoodFactory(DESICompressedBAOLikelihood, 'desi_bao_elg_z1', kw_like={'cosmo': 'external', 'tracers': ['elg_z1'], 'version': 'v1.5'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
DESICompressedBAOLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'DESICompressedBAOLikelihood')
desi_bao_qso_z0 = CobayaLikelihoodFactory(DESICompressedBAOLikelihood, 'desi_bao_qso_z0', kw_like={'cosmo': 'external', 'tracers': ['qso_z0'], 'version': 'v1.5'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
DESICompressedBAOLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'DESICompressedBAOLikelihood')
desi_bao_lya_z0 = CobayaLikelihoodFactory(DESICompressedBAOLikelihood, 'desi_bao_lya_z0', kw_like={'cosmo': 'external', 'tracers': ['lya_z0'], 'version': 'v1.5'}, module=__name__, kw_cobaya=None)

