# NOTE: This code has been automatically generated by desilike.bindings.cobaya.factory.CobayaLikelihoodGenerator
from desilike.bindings.cobaya.factory import CobayaLikelihoodFactory

from desilike.bindings.base import load_from_file
DESIFSLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_fs_bao.py', 'DESIFSLikelihood')
desi_shapefit_joint_all = CobayaLikelihoodFactory(DESIFSLikelihood, 'desi_shapefit_joint_all', kw_like={'cosmo': 'external', 'data_name': '', 'observable_name': 'shapefit-joint', 'tracers': None, 'theory_name': 'reptvelocileptors'}, module=__name__, kw_cobaya={'klim': (0.02, 0.2)})

from desilike.bindings.base import load_from_file
DESIFSLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_fs_bao.py', 'DESIFSLikelihood')
desi_shapefit_joint_all_nolya = CobayaLikelihoodFactory(DESIFSLikelihood, 'desi_shapefit_joint_all_nolya', kw_like={'cosmo': 'external', 'data_name': '', 'observable_name': 'shapefit-joint', 'tracers': ['bgs_z0', 'lrg_z0', 'lrg_z1', 'lrg_z2', 'elg_z1', 'qso_z0'], 'theory_name': 'reptvelocileptors'}, module=__name__, kw_cobaya={'klim': (0.02, 0.2)})

from desilike.bindings.base import load_from_file
DESIFSLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_fs_bao.py', 'DESIFSLikelihood')
desi_shapefit_joint_bgs = CobayaLikelihoodFactory(DESIFSLikelihood, 'desi_shapefit_joint_bgs', kw_like={'cosmo': 'external', 'data_name': '', 'observable_name': 'shapefit-joint', 'tracers': ['bgs_z0'], 'theory_name': 'reptvelocileptors'}, module=__name__, kw_cobaya={'klim': (0.02, 0.2)})

from desilike.bindings.base import load_from_file
DESIFSLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_fs_bao.py', 'DESIFSLikelihood')
desi_shapefit_joint_lrg = CobayaLikelihoodFactory(DESIFSLikelihood, 'desi_shapefit_joint_lrg', kw_like={'cosmo': 'external', 'data_name': '', 'observable_name': 'shapefit-joint', 'tracers': ['lrg_z0', 'lrg_z1', 'lrg_z2'], 'theory_name': 'reptvelocileptors'}, module=__name__, kw_cobaya={'klim': (0.02, 0.2)})

from desilike.bindings.base import load_from_file
DESIFSLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_fs_bao.py', 'DESIFSLikelihood')
desi_shapefit_joint_lrg_z0 = CobayaLikelihoodFactory(DESIFSLikelihood, 'desi_shapefit_joint_lrg_z0', kw_like={'cosmo': 'external', 'data_name': '', 'observable_name': 'shapefit-joint', 'tracers': ['lrg_z0'], 'theory_name': 'reptvelocileptors'}, module=__name__, kw_cobaya={'klim': (0.02, 0.2)})

from desilike.bindings.base import load_from_file
DESIFSLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_fs_bao.py', 'DESIFSLikelihood')
desi_shapefit_joint_lrg_z1 = CobayaLikelihoodFactory(DESIFSLikelihood, 'desi_shapefit_joint_lrg_z1', kw_like={'cosmo': 'external', 'data_name': '', 'observable_name': 'shapefit-joint', 'tracers': ['lrg_z1'], 'theory_name': 'reptvelocileptors'}, module=__name__, kw_cobaya={'klim': (0.02, 0.2)})

from desilike.bindings.base import load_from_file
DESIFSLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_fs_bao.py', 'DESIFSLikelihood')
desi_shapefit_joint_lrg_z2 = CobayaLikelihoodFactory(DESIFSLikelihood, 'desi_shapefit_joint_lrg_z2', kw_like={'cosmo': 'external', 'data_name': '', 'observable_name': 'shapefit-joint', 'tracers': ['lrg_z2'], 'theory_name': 'reptvelocileptors'}, module=__name__, kw_cobaya={'klim': (0.02, 0.2)})

from desilike.bindings.base import load_from_file
DESIFSLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_fs_bao.py', 'DESIFSLikelihood')
desi_shapefit_joint_elg = CobayaLikelihoodFactory(DESIFSLikelihood, 'desi_shapefit_joint_elg', kw_like={'cosmo': 'external', 'data_name': '', 'observable_name': 'shapefit-joint', 'tracers': ['elg_z1'], 'theory_name': 'reptvelocileptors'}, module=__name__, kw_cobaya={'klim': (0.02, 0.2)})

from desilike.bindings.base import load_from_file
DESIFSLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_fs_bao.py', 'DESIFSLikelihood')
desi_shapefit_joint_qso = CobayaLikelihoodFactory(DESIFSLikelihood, 'desi_shapefit_joint_qso', kw_like={'cosmo': 'external', 'data_name': '', 'observable_name': 'shapefit-joint', 'tracers': ['qso_z0'], 'theory_name': 'reptvelocileptors'}, module=__name__, kw_cobaya={'klim': (0.02, 0.2)})

