# NOTE: This code has been automatically generated by desilike.bindings.cobaya.factory.CobayaLikelihoodGenerator
from desilike.bindings.cobaya.factory import CobayaLikelihoodFactory

from desilike.bindings.base import load_from_file
SNLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'SNLikelihood')
pantheon = CobayaLikelihoodFactory(SNLikelihood, 'pantheon', kw_like={'cosmo': 'external', 'name': 'pantheon'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
SNLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'SNLikelihood')
pantheonplus = CobayaLikelihoodFactory(SNLikelihood, 'pantheonplus', kw_like={'cosmo': 'external', 'name': 'pantheonplus'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
SNLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'SNLikelihood')
pantheonplusshoes = CobayaLikelihoodFactory(SNLikelihood, 'pantheonplusshoes', kw_like={'cosmo': 'external', 'name': 'pantheonplusshoes'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
SNLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'SNLikelihood')
union3 = CobayaLikelihoodFactory(SNLikelihood, 'union3', kw_like={'cosmo': 'external', 'name': 'union3'}, module=__name__, kw_cobaya=None)

from desilike.bindings.base import load_from_file
SNLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'SNLikelihood')
desy5 = CobayaLikelihoodFactory(SNLikelihood, 'desy5', kw_like={'cosmo': 'external', 'name': 'desy5'}, module=__name__, kw_cobaya=None)

