# NOTE: This code has been automatically generated by desilike.bindings.cosmosis.factory.CosmoSISLikelihoodGenerator
from desilike.bindings.cosmosis.factory import CosmoSISLikelihoodFactory

from desilike.bindings.base import load_from_file
DESICompressedBAOLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'DESICompressedBAOLikelihood')
desi_bao_lrg_z2 = CosmoSISLikelihoodFactory(DESICompressedBAOLikelihood, 'desi_bao_lrg_z2', kw_like={'cosmo': 'external', 'tracers': ['lrg_z2'], 'version': 'v1.5'}, module=__name__)

setup, execute, cleanup = desi_bao_lrg_z2.build_module()

