# NOTE: This code has been automatically generated by desilike.bindings.cosmosis.factory.CosmoSISLikelihoodGenerator
from desilike.bindings.cosmosis.factory import CosmoSISLikelihoodFactory

from desilike.bindings.base import load_from_file
DESIFSLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_fs_bao.py', 'DESIFSLikelihood')
desi_shapefit_joint_qso = CosmoSISLikelihoodFactory(DESIFSLikelihood, 'desi_shapefit_joint_qso', kw_like={'cosmo': 'external', 'data_name': '', 'observable_name': 'shapefit-joint', 'tracers': ['qso_z0'], 'theory_name': 'reptvelocileptors'}, module=__name__)

setup, execute, cleanup = desi_shapefit_joint_qso.build_module()

