# NOTE: This code has been automatically generated by desilike.bindings.cosmosis.factory.CosmoSISLikelihoodGenerator
from desilike.bindings.cosmosis.factory import CosmoSISLikelihoodFactory

from desilike.bindings.base import load_from_file
SNLikelihood = load_from_file('/global/cfs/cdirs/desicollab/users/hernannb/__FOLPS_tutorial/part3/desi-y1-kp-main/desi_y1_cosmo_bindings/bindings_bao.py', 'SNLikelihood')
pantheonplus = CosmoSISLikelihoodFactory(SNLikelihood, 'pantheonplus', kw_like={'cosmo': 'external', 'name': 'pantheonplus'}, module=__name__)

setup, execute, cleanup = pantheonplus.build_module()

